import Vue from "vue";
import {
  Button,
  Toast,
  Row,
  Col,
  DropdownMenu,
  DropdownItem,
  RadioGroup,
  Radio,
  Field,
  Checkbox,
  Icon,
  Tab,
  Tabs,
  Popup,
  Search,
  Swipe,
  SwipeItem,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Sidebar,
  SidebarItem,
  Progress,
  Rate,
  Collapse,
  CollapseItem,
  Calendar,
  Cell,
  CellGroup,
  ActionSheet,
  Area,
  Card,
  SubmitBar,
  Uploader,
  Picker,
} from "vant";

Vue.use(Button);
Vue.use(Toast);
Vue.use(Row);
Vue.use(Col);
Vue.use(DropdownMenu).use(DropdownItem);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(Field);
Vue.use(Checkbox);
Vue.use(Icon);
Vue.use(Tab).use(Tabs);
Vue.use(Popup);
Vue.use(Search);
Vue.use(Swipe).use(SwipeItem);
Vue.use(GoodsAction)
  .use(GoodsActionIcon)
  .use(GoodsActionButton);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Progress);
Vue.use(Rate);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Calendar);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(ActionSheet);
Vue.use(Area);
Vue.use(Card);
Vue.use(SubmitBar);
Vue.use(Uploader);
Vue.use(Picker);
